/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;
import java.sql.*;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Nasser
 */
public class c_show extends javax.swing.JPanel {

    /**
     * Creates new form c_show
     */
    int id;
    public c_show(int id) {
        initComponents();
        
        this.id=id;
    }
    public void notes() {
         try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String username = "admin";
            String password = "admin";
            java.sql.Connection c = DriverManager.getConnection(url, username, password);
            java.sql.Statement stmt = c.createStatement();
            String sql ="select * from course";
            ResultSet s = stmt.executeQuery(sql);
           
            String name="";
            LocalDate ndate;
            LocalDate edate;
            LocalDate sdate;
            
            String note1="";
            String k1="";
            String note2="";
            String k2="";
            while(s.next())
            {
                name=s.getString("cou_name");
                ndate=LocalDate.now();
                edate=LocalDate.parse(s.getString("end_course_date"));
                Period p = Period.between(ndate, edate);
                
                if(p.getYears()==0 && Math.abs(p.getMonths())<=4)
                {
                    k1="course "+name+" is abote to end it Remains "+Math.abs(p.getMonths())+" months and "+Math.abs(p.getDays())+"days \n";
                     note1+=k1;
                } 
                sdate=LocalDate.parse(s.getString("start_course_date"));
                p = Period.between(ndate, sdate);
                
                if(p.getYears()==0 && Math.abs(p.getMonths())<=4)
                {
                    k2="course "+name+" is abote to start it Remains "+Math.abs(p.getMonths())+" months and "+Math.abs(p.getDays())+"days \n";
                     note2+=k2;
                }  
            }
            jTextArea1.setText(note1);
            jTextArea2.setText(note2);
            System.out.print(note1);
            System.out.print(note2);
            c.close();
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }
    public void show_c()
    {
    
    try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String username = "admin";
            String password = "admin";
            Connection c = DriverManager.getConnection(url, username, password);
            Statement stmt = c.createStatement();
             
            Object [] oc=new Object[6];
            String sql="select * from course";
            ResultSet s=stmt.executeQuery(sql);
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            model1.setRowCount(0);
            while (s.next()) {
                oc[0]=s.getInt("cuo_id");
                oc[1]=s.getString("cou_name");
                oc[2]=s.getInt("course_price");
                oc[3]=s.getString("parent_course_name");
                oc[4]=s.getInt("room");
                oc[5]=s.getInt("instructor_id");
                model1.addRow(oc);   
        }
            c.close();
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "price", "perant name", "room", "instractor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("notes");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
