/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import pl_project.course;
import pl_project.instructor;
import pl_project.student;
/**
 *
 * @author Ahmed Nasser
 */
public class edit_std_grade extends javax.swing.JPanel {

    /**
     * Creates new form edit_std_grade
     */
    int id;
    
    public edit_std_grade(int id) {
        this.id=id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        grade = new javax.swing.JTextField();
        new_grade = new javax.swing.JButton();
        l = new javax.swing.JLabel();

        jLabel5.setText("student id");

        std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_idActionPerformed(evt);
            }
        });

        jLabel6.setText("course id");

        jLabel7.setText("new grade");

        new_grade.setText("set");
        new_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_gradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(new_grade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(grade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_grade)
                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void new_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_gradeActionPerformed
        // TODO add your handling code here:
        
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String username = "admin";
            String password = "admin";
            Connection c = DriverManager.getConnection(url, username, password);
            Statement stmt = c.createStatement();
            
            int i=0;
            String sq3 ="select count (cuo_id )as co from course join instructor on inst_id=instructor_id where inst_id="+this.id;
            ResultSet s3 = stmt.executeQuery(sq3);
            if(s3.next())
                i=s3.getInt("co");
            System.out.println(i);
            int []course_id=new int[i];
            String sql = "select cuo_id from course join instructor on inst_id=instructor_id where inst_id=" + this.id;
            ResultSet s = stmt.executeQuery(sql);
            
            int p=0;
            while(s.next())
            {
                 course_id[p]=s.getInt("cuo_id");
                 p++;
            }
            
           int []arr=new int[50];
           int m=0;
           for (int l=0;l<course_id.length;l++)
           {
                String sql2="select student.std_id from student join std_reg_cou on std_id=student_id join course on course_id=cuo_id where cuo_id="+course_id[l];
                ResultSet s2=stmt.executeQuery(sql2);
                while(s2.next())
                {
                    arr[m]=s2.getInt("std_id");
                    m++;
                }
           }
           
            boolean x=false;
            boolean y=false;
            for(int k=0;k<course_id.length;k++)
            {
                if(course_id[k]==Integer.parseInt(c_id.getText()))
                {
                    y=true;
                    for(int j=0;j<arr.length;j++)
                    {
                        if(Integer.parseInt(std_id.getText())==arr[j])
                            x=true;
                    }
                }
            }
            if(y)
            {              
                if(x)
                {
                    String sql3 ="update std_reg_cou set std_reg_cou.cource_grade ="+grade.getText()+" where std_reg_cou.course_id="+c_id.getText()+"and std_reg_cou.student_id="+std_id.getText();
                    stmt.execute(sql3);
                    l.setText("updated");
                }
                else
                {
                   l.setText("invalid student id");
                }
            }else
                l.setText("invalid course id");         
            c.close();     
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_new_gradeActionPerformed

    private void std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel l;
    private javax.swing.JButton new_grade;
    private javax.swing.JTextField std_id;
    // End of variables declaration//GEN-END:variables
}
