/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;
import java.sql.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import pl_project.course;
import pl_project.instructor;
import pl_project.student;

/**
 *
 * @author Ahmed Nasser
 */
public class edit_inst extends javax.swing.JPanel {

    /**
     * Creates new form edit_inst
     */
    int id;
    public edit_inst(int id) {
        this.id=id;
        initComponents();
         try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String username = "admin";
            String password = "admin";
            Connection c = DriverManager.getConnection(url, username, password);
            Statement stmt = c.createStatement();
            
            String sql ="select * from instructor where inst_id="+this.id;
            ResultSet s= stmt.executeQuery(sql);
            if(s.next())
            {
                inst_name.setText(s.getString("inst_name"));
                inst_username.setText(s.getString("inst_userName"));
                inst_pass.setText(s.getInt("inst_pass")+"");  
            }
          
            c.close();     
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inst_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inst_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inst_pass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        updat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        inst_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inst_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Instructor Name");

        jLabel5.setText("Instructor UserName");

        jLabel6.setText("Password");

        updat.setText("Update");
        updat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inst_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inst_username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inst_pass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updat)
                        .addGap(69, 69, 69)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updat)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inst_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inst_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inst_nameActionPerformed

    private void updatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatActionPerformed
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String username = "admin";
            String password = "admin";
            Connection c = DriverManager.getConnection(url, username, password);
            Statement stmt = c.createStatement();
            
            String sql ="update instructor set inst_name='"+inst_name.getText()+"',inst_pass="+inst_pass.getText()+",inst_userName='"+inst_username.getText()+"' where inst_id="+this.id;
          stmt.execute(sql);
          jLabel1.setText("updated");
            c.close();     
        }
        catch(SQLException e)
        {
            System.out.print(e);
             jLabel1.setText("invalid user name");
        }
    }//GEN-LAST:event_updatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inst_name;
    private javax.swing.JTextField inst_pass;
    private javax.swing.JTextField inst_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton updat;
    // End of variables declaration//GEN-END:variables
}
