/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import pl_project.course;
import pl_project.instructor;
import pl_project.student;

/**
 *
 * @author Ahmed Nasser
 */
public class inst_std extends javax.swing.JPanel {

    /**
     * Creates new form inst_std
     */
    int id;
    public inst_std(int id) {
        this.id=id;
        initComponents();
    }
     public void print_st () {
        int count = 0;
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=pl_project";
            String user = "admin";
            String pass = "admin";
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement stmt = con.createStatement();
            Statement stmt1 = con.createStatement();
            int i=0;
            String sq3 ="select count (cuo_id )as co from course join instructor on inst_id=instructor_id where inst_id="+this.id;
            ResultSet s3 = stmt.executeQuery(sq3);
            if(s3.next())
                i=s3.getInt("co");
                
            System.out.println(i);
            int []course_id=new int[i];
            String sql = "select cuo_id from course join instructor on inst_id=instructor_id where inst_id=" + this.id;
            ResultSet s = stmt.executeQuery(sql);
            int p=0;
            while(s.next())
            {
                 course_id[p]=s.getInt("cuo_id");
                 p++;
            }
            System.out.println(course_id.length);
            System.out.println("*************");
            DefaultTableModel model1 = (DefaultTableModel) student_info.getModel();
            Object[] data = new Object[6];
            model1.setRowCount(0);
            for (int j = 0; j < course_id.length; j++) {
                System.out.println(course_id[j]);
                System.out.println("#######");
                    String sql2="select course_id,cource_grade ,* from student join std_reg_cou on std_id=student_id join course on course_id=cuo_id where cuo_id="+course_id[j];
                 ResultSet s2=stmt1.executeQuery(sql2);

                 
                 while (s2.next()) {
                     System.out.println(s2.getInt("std_id"));
                     System.out.println("&&&&&&&&&&");
                     
                     data[0] = s2.getInt("std_id");
                     data[1] = s2.getString("std_name");
                     data[2] = s2.getString("std_userName");
                     data[3] = s2.getInt("std_pass");
                     data[4]=s2.getInt("course_id");
                     data[5]=s2.getInt("cource_grade");
                     model1.addRow(data);
               } 
            }   
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        student_info = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        student_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "UserName", "password", "course id", "grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(student_info);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        print_st();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable student_info;
    // End of variables declaration//GEN-END:variables
}
